name: GitHubPages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          # hugo-version: # optional, default is latest
          # Download (if necessary) and use Hugo extended version. Example: true
          hugo-version: '0.119.0'
          extended: true
          
      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: siriusol/siriusol.github.io
          publish_branch: master
          publish_dir: ./public
permissions:
  contents: write
