name: GitHubPages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Hugo Actions
        # You may pin to the exact commit or the version.
        # uses: srt32/hugo-action@45dd72ab904158d21657b29c5aa67007a8fcdaba
        uses: srt32/hugo-action@v0.0.3
          
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          # hugo-version: # optional, default is latest
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true
          
      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: siriusol/siriusol.github.io
          publish_branch: master
          publish_dir: ./public
